name: learn-github-actions
run-name: test-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: echo "hello world"
      - name: 'Test Shell Run'
        shell: bash
        run: |
          echo 'hello world'
          echo 'hello world'
          echo 'hello world'
          echo 'hello world'
